# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- stable

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Checkmarx AST@3
  inputs:
    CheckmarxService: 'Checkmarx One'
    projectName: '$(Build.Repository.Name)'
    branchName: '$(Build.SourceBranchName)'
    tenantName: 'nfr_lugapel-ast'
